name: Seer
favicon: null
layout_spectrum: 0.8820321604143828
typography_spectrum: 0.19560172595083714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.21007125359028578
  lightness: 0.6225189890246838
  saturation: 0.23528725979849696
  rhythmicContrast: 0.35856045922264457
purpose: []
